apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dfnx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dfnx
    app.kubernetes.io/part-of: byoc-app-jtrz
  name: dfnx
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: dfnx
status:
  loadBalancer: {}
